---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 7474, host: 7474}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[neo4j::default]
